theme: jekyll-theme-minimal
title: Gregor BÃ¶s
description: Welcome to my academic website.
email: gregor.boes@kcl.ac.uk

url:                 http://gboes.github.io
baseurl:             ''
markdown: CommonMarkGhPages
exclude:
 - README.md

# Google Analytics:
google_analytics: UA-145857720-1
